"""Pydantic schemas for API."""
from app.schemas.novel import (
    NovelCreate,
    NovelUpdate,
    NovelResponse,
    ChapterResponse,
    GenerateRequest,
    GenerateResponse,
    GenerationStatusResponse,
    CharacterProfileResponse,
)
from app.schemas.storyboard import (
    StoryboardCreateRequest,
    StoryboardProjectResponse,
    StoryboardGenerateResponse,
    StoryboardStyleRecommendationRequest,
    StoryboardStyleRecommendationResponse,
    StoryboardTaskStatusResponse,
    StoryboardVersionResponse,
    StoryboardShotResponse,
    StoryboardCharacterPromptResponse,
    StoryboardCharacterGenerateResponse,
    StoryboardOptimizeResponse,
)

__all__ = [
    "NovelCreate",
    "NovelUpdate",
    "NovelResponse",
    "ChapterResponse",
    "GenerateRequest",
    "GenerateResponse",
    "GenerationStatusResponse",
    "CharacterProfileResponse",
    "StoryboardCreateRequest",
    "StoryboardProjectResponse",
    "StoryboardGenerateResponse",
    "StoryboardStyleRecommendationRequest",
    "StoryboardStyleRecommendationResponse",
    "StoryboardTaskStatusResponse",
    "StoryboardVersionResponse",
    "StoryboardShotResponse",
    "StoryboardCharacterPromptResponse",
    "StoryboardCharacterGenerateResponse",
    "StoryboardOptimizeResponse",
]
